---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:


jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: run_tests.sh

  tests:
    name: integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
      - name: Run integration tests
        run: ./run_tests.py
